---
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "Before you can build Suricata for your system, ensure that you have everything you need for the installation"
  package:
    name:
      - suricata
    state: present
- name: "Enable suricata service"
  service:
    name: "suricata"
    enabled: yes
    state: started
- name: Copy suricata rules
  ansible.builtin.copy:
    src: ../custom_rules/my.rules
    dest: /etc/suricata/rules/suricata.rules
    owner: root
    group: root
    mode: '0644'
- name: "Restart suricata service"
  service:
    name: "suricata"
    enabled: yes
    state: restarted

